---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test
  labels:
    name: test
  namespace: llama2-infra
spec:
  replicas: 10
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
      - name: test
        image: pengbai/docker-supermario
        ports:
        - name: test
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: test-instance
  labels:
    name: test-instance
  namespace: llama2-infra
spec:
  externalIPs:
{% for node in k8s_nodes %}
    - {{ node.ip }}
{% endfor %}
  ports:
  - port: 8600  # The port visible on the private net.
    targetPort: 8080   # the port that will be reached in the pod
    name: port8600
  selector:
    name: test
